### ISSUE TITLE
"couldn't find fanout table" on PackIndexFile_sha_to_index()

### ISSUE THREAD

**Issue by nareshov** [gitpython-developers/gitdb#21]
Here's a stack trace I'm seeing on upgrading Gerrit to a recent release, this looks gitdb specific so thought I'd ask here in case a workaround is known:

```
opsgerrit@IAD01-INSTALL01:/opt/opsgerrit/hooks/change-merged.d$ tail -f /opt/opsgerrit/logs/error_log 
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return self._db_query(sha).info(sha)
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/base.py", line 239, in _db_query
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     if db.has_object(sha):
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/pack.py", line 88, in has_object
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     self._pack_info(sha)
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/pack.py", line 71, in _pack_info
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     index = item[2](sha)
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/pack.py", line 492, in sha_to_index
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return PackIndexFile_sha_to_index(self, sha)
[2015-10-09 02:37:26,928] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output: ValueError: Couldn't obtain fanout table


[2015-10-09 02:56:56,708] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output: running: /opt/opsgerrit/hooks/change-merged.d/preseed-master-activate
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output: running: /opt/opsgerrit/hooks/change-merged.d/puppet-production-activate
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output: Traceback (most recent call last):
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/hooks/change-merged.d/puppet-production-activate", line 107, in <module>
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     process_puppet_production(args)
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/hooks/change-merged.d/puppet-production-activate", line 86, in process_puppet_production
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     commit = source_repo.commit(args.commit)
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 378, in commit
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return self.rev_parse(str(rev)+"^0")
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/fun.py", line 151, in rev_parse
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     obj = name_to_object(repo, rev[:start])
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/fun.py", line 89, in name_to_object
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return Object.new_from_sha(repo, hex_to_bin(hexsha))
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/base.py", line 64, in new_from_sha
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     oinfo = repo.odb.info(sha1)
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/base.py", line 256, in info
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return self._db_query(sha).info(sha)
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/base.py", line 239, in _db_query
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     if db.has_object(sha):
[2015-10-09 02:56:56,709] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/pack.py", line 88, in has_object
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     self._pack_info(sha)
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/db/pack.py", line 71, in _pack_info
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     index = item[2](sha)
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:   File "/opt/opsgerrit/pyenv/local/lib/python2.7/site-packages/gitdb-0.5.4-py2.7-linux-x86_64.egg/gitdb/pack.py", line 492, in sha_to_index
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output:     return PackIndexFile_sha_to_index(self, sha)
[2015-10-09 02:56:56,710] INFO  com.google.gerrit.common.ChangeHookRunner : hook[change-merged] output: ValueError: Couldn't obtain fanout table
```

**Comment by nareshov** [comment]
I had to run a `gerrit gc' and that fixed this. Not documented and was a complete poke in the dark.

**Comment by Byron** [comment]
Thanks for letting me know.
I believe that `gc` removed/fixed the problematic package file, and thus fixed the problem.

If you see issues like this in future, it could be due to a changed package format. In that case, you can instantiate the git repository with `Repo(path, odbt=GitCmdObjectDB)` to avoid the pure-python implementation.
